-- MySQL Script generated by MySQL Workbench
-- Thu Apr  9 15:26:55 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema hibernate
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hibernate` ;

-- -----------------------------------------------------
-- Schema hibernate
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hibernate` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `hibernate` ;

-- -----------------------------------------------------
-- Table `hibernate`.`estilo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hibernate`.`estilo` ;

CREATE TABLE IF NOT EXISTS `hibernate`.`estilo` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hibernate`.`cerveja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hibernate`.`cerveja` ;

CREATE TABLE IF NOT EXISTS `hibernate`.`cerveja` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `comissao` DOUBLE NOT NULL,
  `content_type` VARCHAR(100) NULL DEFAULT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `foto` VARCHAR(100) NULL DEFAULT NULL,
  `nome` VARCHAR(80) NOT NULL,
  `origem` VARCHAR(50) NOT NULL,
  `quantidade_estoque` INT NULL DEFAULT NULL,
  `sabor` VARCHAR(50) NOT NULL,
  `sku` VARCHAR(50) NOT NULL,
  `teor_alcoolico` DOUBLE NOT NULL,
  `valor` DOUBLE NOT NULL,
  `codigo_estilo` INT NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `FKr8cbc1uajb471swu38vd6olg` (`codigo_estilo` ASC) VISIBLE,
  CONSTRAINT `FKr8cbc1uajb471swu38vd6olg`
    FOREIGN KEY (`codigo_estilo`)
    REFERENCES `hibernate`.`estilo` (`codigo`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hibernate`.`estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hibernate`.`estado` ;

CREATE TABLE IF NOT EXISTS `hibernate`.`estado` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `sigla` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hibernate`.`cidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hibernate`.`cidade` ;

CREATE TABLE IF NOT EXISTS `hibernate`.`cidade` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `codigo_estado` INT NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `UK_lwg97fq9vkwb5vlqo59krrxoa` (`nome` ASC) VISIBLE,
  INDEX `FK3p3ii5fk4vpyyp0bju26kggbb` (`codigo_estado` ASC) VISIBLE,
  CONSTRAINT `FK3p3ii5fk4vpyyp0bju26kggbb`
    FOREIGN KEY (`codigo_estado`)
    REFERENCES `hibernate`.`estado` (`codigo`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hibernate`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hibernate`.`cliente` ;

CREATE TABLE IF NOT EXISTS `hibernate`.`cliente` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `cep` VARCHAR(15) NULL DEFAULT NULL,
  `complemento` VARCHAR(20) NULL DEFAULT NULL,
  `cpf_cnpj` VARCHAR(30) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `logradouro` VARCHAR(50) NULL DEFAULT NULL,
  `nome` VARCHAR(80) NOT NULL,
  `numero` VARCHAR(15) NULL DEFAULT NULL,
  `telefone` VARCHAR(20) NULL DEFAULT NULL,
  `tipo_pessoa` VARCHAR(15) NOT NULL,
  `codigo_cidade` INT NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `FK6xsfn948sdgaetvsvrrdngser` (`codigo_cidade` ASC) VISIBLE,
  CONSTRAINT `FK6xsfn948sdgaetvsvrrdngser`
    FOREIGN KEY (`codigo_cidade`)
    REFERENCES `hibernate`.`cidade` (`codigo`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hibernate`.`grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hibernate`.`grupo` ;

CREATE TABLE IF NOT EXISTS `hibernate`.`grupo` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hibernate`.`permissao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hibernate`.`permissao` ;

CREATE TABLE IF NOT EXISTS `hibernate`.`permissao` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hibernate`.`grupo_permissao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hibernate`.`grupo_permissao` ;

CREATE TABLE IF NOT EXISTS `hibernate`.`grupo_permissao` (
  `permissao_codigo` INT NOT NULL,
  `grupo_codigo` INT NOT NULL,
  PRIMARY KEY (`grupo_codigo`, `permissao_codigo`),
  INDEX `FKr9d76c2nbpmre6k8e000k58hr` (`permissao_codigo` ASC) VISIBLE,
  CONSTRAINT `FK2qeqbchnt7rnh865jn4sgr42u`
    FOREIGN KEY (`grupo_codigo`)
    REFERENCES `hibernate`.`grupo` (`codigo`),
  CONSTRAINT `FKr9d76c2nbpmre6k8e000k58hr`
    FOREIGN KEY (`permissao_codigo`)
    REFERENCES `hibernate`.`permissao` (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hibernate`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hibernate`.`usuario` ;

CREATE TABLE IF NOT EXISTS `hibernate`.`usuario` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `ativo` INT NOT NULL,
  `data_nascimento` DATE NULL DEFAULT NULL,
  `email` VARCHAR(50) NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hibernate`.`venda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hibernate`.`venda` ;

CREATE TABLE IF NOT EXISTS `hibernate`.`venda` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `data_criacao` DATETIME(6) NOT NULL,
  `data_hora_entrega` DATETIME(6) NULL DEFAULT NULL,
  `observacao` VARCHAR(200) NULL DEFAULT NULL,
  `status` VARCHAR(30) NOT NULL,
  `valor_desconto` DOUBLE NULL DEFAULT NULL,
  `valor_frete` DOUBLE NULL DEFAULT NULL,
  `valor_total` DOUBLE NOT NULL,
  `Codigo_cliente` INT NULL DEFAULT NULL,
  `codigo_usuario` INT NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `FKeol4xjtqvrx0toqkm77ospapl` (`Codigo_cliente` ASC) VISIBLE,
  INDEX `FK9gr1cxfscbamxiroywi3tpoo3` (`codigo_usuario` ASC) VISIBLE,
  CONSTRAINT `FK9gr1cxfscbamxiroywi3tpoo3`
    FOREIGN KEY (`codigo_usuario`)
    REFERENCES `hibernate`.`usuario` (`codigo`),
  CONSTRAINT `FKeol4xjtqvrx0toqkm77ospapl`
    FOREIGN KEY (`Codigo_cliente`)
    REFERENCES `hibernate`.`cliente` (`codigo`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hibernate`.`itemvenda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hibernate`.`itemvenda` ;

CREATE TABLE IF NOT EXISTS `hibernate`.`itemvenda` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `quantidade` INT NOT NULL,
  `valor_unitario` DOUBLE NOT NULL,
  `codigo_cerveja` INT NULL DEFAULT NULL,
  `codigo_venda` INT NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `FK62eleexfd0xp5ywrecrkov49c` (`codigo_cerveja` ASC) VISIBLE,
  INDEX `FKena1k6tylsxx0hbbpk5bdna1n` (`codigo_venda` ASC) VISIBLE,
  CONSTRAINT `FK62eleexfd0xp5ywrecrkov49c`
    FOREIGN KEY (`codigo_cerveja`)
    REFERENCES `hibernate`.`cerveja` (`codigo`),
  CONSTRAINT `FKena1k6tylsxx0hbbpk5bdna1n`
    FOREIGN KEY (`codigo_venda`)
    REFERENCES `hibernate`.`venda` (`codigo`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hibernate`.`usuario_grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hibernate`.`usuario_grupo` ;

CREATE TABLE IF NOT EXISTS `hibernate`.`usuario_grupo` (
  `usuario_codigo` INT NOT NULL,
  `grupo_codigo` INT NOT NULL,
  PRIMARY KEY (`grupo_codigo`, `usuario_codigo`),
  INDEX `FK35bqdt62nnr1mnjw7m1fqq6m8` (`usuario_codigo` ASC) VISIBLE,
  CONSTRAINT `FK35bqdt62nnr1mnjw7m1fqq6m8`
    FOREIGN KEY (`usuario_codigo`)
    REFERENCES `hibernate`.`usuario` (`codigo`),
  CONSTRAINT `FKaarq4r483vyj0bhfj4wsnvmux`
    FOREIGN KEY (`grupo_codigo`)
    REFERENCES `hibernate`.`grupo` (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
